# Generated by Django 3.2.16 on 2024-01-04 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AttributePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seo.attributename",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255, unique=True)),
                ("is_pattern", models.BooleanField(default=False)),
                ("model_pk", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "models_to_select",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"app_label": "api"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TagType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("self_closing", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "attribute_pairs",
                    models.ManyToManyField(related_name="tags", to="seo.AttributePair"),
                ),
                ("pages", models.ManyToManyField(related_name="tags", to="seo.Page")),
                (
                    "tag_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="seo.tagtype"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attributepair",
            name="attribute_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="seo.attributevalue"
            ),
        ),
        migrations.AddField(
            model_name="attributepair",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="seo.tag"
            ),
        ),
    ]
