# Generated by Django 3.2.16 on 2024-01-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributename",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="attributevalue",
            name="value",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="tagtype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
