# Generated by Django 3.2.16 on 2024-01-04 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seo", "0002_auto_20240104_1407"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attributepair",
            name="tag",
        ),
    ]
