# Generated by Django 3.2.16 on 2024-01-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seo", "0004_alter_attributepair_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attributepair",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="attributepair",
            name="attribute_name",
        ),
        migrations.RemoveField(
            model_name="attributepair",
            name="attribute_value",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="attribute_pairs",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="pages",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="tag_type",
        ),
        migrations.AddField(
            model_name="page",
            name="tags",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="AttributeName",
        ),
        migrations.DeleteModel(
            name="AttributePair",
        ),
        migrations.DeleteModel(
            name="AttributeValue",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.DeleteModel(
            name="TagType",
        ),
    ]
