# Generated by Django 3.2.16 on 2024-01-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seo", "0005_auto_20240104_1738"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
