# Generated by Django 3.2.16 on 2024-01-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_movie_poster_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='extras',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
