# Generated by Django 3.2.16 on 2024-01-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_alter_movielist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="visible_in_home_page",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contest",
            name="visible_in_top_creators",
            field=models.BooleanField(default=False),
        ),
    ]
